services:
  mysql:
    image: mysql:8.3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      WAIT_HOSTS: mysql:3306

  migration:
    build: .
    profiles: ["migration"]
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_COMMAND: "npm run migration:run"
    entrypoint: ["/wait"]

volumes:
  mysql_data: